### ISSUE TITLE
fauxmoESP with WiFiManager requires a hard reset before Alexa Discovery

### ISSUE THREAD

**Issue by ddweber456** [vintlabs/fauxmoESP#123] opened 2020-11-12 04:35 UTC
@pvint, I have a strange issue going on with the use of WiFiManaager autoConnect (0.15.0) and using fauxmoESP (3.1.1).  If my sketch successfully complete autoConnect and saves the WiFi credentials and any custom parameters, I can't get Alexa to discover the Fauxmo devices until after I do a hard reset.   Is there something that autoConnect uses that the UDO doesn't like or the other way around?

**Comment by pvint** [comment] 2020-11-12 16:18
That's pretty strange. Can you post your sketch?

**Comment by ddweber456** [comment] 2020-11-12 19:20
Here is the sketch.

```
#include <LittleFS.h> 
#include <ArduinoJson.h>        // https://github.com/bblanchon/ArduinoJson  Version 5.13.5 
#include <ESP8266WiFi.h>        //ESP8266 Core WiFi Library 
#include <WiFiManager.h>        //https://github.com/tzapu/WiFiManager WiFi Configuration Magic
#include <DNSServer.h>          //Local DNS Server used for redirecting all requests to the configuration portal
#include <ESP8266WebServer.h>   //Local WebServer used to serve the configuration portal
#include <fauxmoESP.h>          //ESP8266 & ESP32 Alexa
//#include <EEPROM.h> 

fauxmoESP fauxmo;

// Variable to store the HTTP request
String header;

// Auxiliar variables to store the current output state
String outputState = "off";

// Assign custom parameter "smart_home_phrase" variables for Alexa
char smart_home_phrase[40] = "remote one";        //Custom Parameter ---------------------------------
char double_press[40] = "double press";           //Custom Parameter ---------------------------------

//flag for saving data
bool shouldSaveConfig = false;

// -----------------------------------------------------------------------------

#define SERIAL_BAUDRATE      115200
#define PIN_DOOR             12
#define PIN_REMOTE           5
#define PIN_PARKDOOR         14
#define wifiReSetPIN         3 

#define ID_REMOTE              smart_home_phrase            // Alexa phrases
#define ID_PARKDOOR            double_press                 // Alexa phrases


int remotePressHold =     850;     // time to hold remote to send RF singal
int swingDelay =          6000;    // time to delay second remotePress to hold the door open
int blinkTime =           1;       // blink on duration

int remotePress=LOW;
int parkDoor=LOW;
int ledState=HIGH;
int setParkFlag=0;
int setRemoteFlag=0;
bool buttonFlag = false;
int longButton = 4000;
int button = LOW;

unsigned long previousMillis = 0;     // will store the last time Remote was updated
unsigned long lastLEDMillis = 0;      // will store the last time the LED was updated
unsigned long buttonMillis = 0;       // will store the last time Remote was updated
unsigned long interval = 0;           // place holder, will be updated in the LED blink

    // WiFiManager
    
    WiFiManager wifiManager;
  
//>>>>>>>>  callback notifying us of the need to save config
void saveConfigCallback () {
  Serial.println("Should save config");
  shouldSaveConfig = true;
}

void setup() {

    Serial.begin(SERIAL_BAUDRATE);
    Serial.println();

  //read configuration from FS json
  Serial.println("Mounting FS...");

  if (SPIFFS.begin()) {
    Serial.println("Mounted SPIFFS file system");
    if (SPIFFS.exists("/config.json")) {
      //file exists, reading and loading
      Serial.println("Reading config file");
      File configFile = SPIFFS.open("/config.json", "r");
      if (configFile) {
        Serial.println("Opened config file");
        size_t size = configFile.size();
        // Allocate a buffer to store contents of the file.
        std::unique_ptr<char[]> buf(new char[size]);

        configFile.readBytes(buf.get(), size);
        DynamicJsonBuffer jsonBuffer;
        JsonObject& json = jsonBuffer.parseObject(buf.get());
        json.printTo(Serial);

        
        if (json.success()) {
          Serial.println("\nparsed json");
          //strcpy(output, json["output"]);
          strcpy(smart_home_phrase,json["smart_home_phrase"]);    //Custom Parameter --------------------------------
          strcpy(double_press,json["double_press"]);              //Custom Parameter -------------------------------- 
        } else {
          Serial.println("failed to load json config");
        }
      }
    }
  } else {
    Serial.println("failed to mount FS");
  }
  //end read
  
  WiFiManagerParameter custom_smart_home_phrase("smart_home_phrase", "smart home phrase", smart_home_phrase, 40); 
  WiFiManagerParameter custom_double_press("double_press", "double press", double_press, 40);                      

    // LEDs and PINs used for logic
    pinMode(2, OUTPUT);                // on-board LED
    pinMode(PIN_DOOR, OUTPUT);         // updated only by Alexa
    pinMode(PIN_REMOTE, OUTPUT);
    pinMode(PIN_PARKDOOR, OUTPUT);     // updated only by Alexa
    digitalWrite(PIN_DOOR, LOW);
    digitalWrite(PIN_REMOTE, LOW);
    digitalWrite(PIN_PARKDOOR, LOW);
    digitalWrite(2, LOW);              // LOW = LED on
    pinMode(wifiReSetPIN, OUTPUT);
    digitalWrite(wifiReSetPIN, LOW);    


  //set config save notify callback
  wifiManager.setSaveConfigCallback(saveConfigCallback);
  
  //add all your parameters here
  wifiManager.addParameter(&custom_smart_home_phrase);       
  wifiManager.addParameter(&custom_double_press);            

   wifiManager.setTimeout(120);   // time the AP will be active, waiting for a AP connection and wifi config
   wifiManager.setConfigPortalTimeout(120);
   
  if(!wifiManager.autoConnect("APSetup WIFI MiniTech", "WIFISwitch")) {
    Serial.println("failed to connect 1st time after BOOT and hit timeout");
    Serial.println("in 3 sec, try again to connect to WiFi with saved credintials");
    digitalWrite(2, HIGH);
    delay(3000);
    digitalWrite(2, LOW);
    ESP.restart();
  }
 
    fauxmo.setPort(80);             // This is required for gen3 devices

    // if you get here you have connected to the WiFi
  Serial.println("WiFi Connected.  yepee!!");
  
    // You have to call enable(true) once you have a WiFi connection
    // You can enable or disable the library at any moment
    // Disabling it will prevent the devices from being discovered and switched
    fauxmo.enable(true);

  //read updated parameters from Json
 
  strcpy(smart_home_phrase, custom_smart_home_phrase.getValue());  
  strcpy(double_press, custom_double_press.getValue());            

  //save the custom parameters to FS
  if (shouldSaveConfig) {
    Serial.println();
    Serial.println("Saving JSON Config");
    DynamicJsonBuffer jsonBuffer;
    JsonObject& json = jsonBuffer.createObject();
    //json["output"] = output;
    json["smart_home_phrase"] = smart_home_phrase;    
    json["double_press"] = double_press;             
        
    File configFile = SPIFFS.open("/config.json", "w");
    if (!configFile) {
      Serial.println("failed to open config file for writing");
    }

    Serial.println("Here is the SAVED JSON File:");
    json.printTo(Serial);
    json.printTo(configFile);
    configFile.close();
    //end save
  }

    Serial.println("Smart Home Phrases: ");     //Proof custom paramter is available ----------------------------
    Serial.print(String(smart_home_phrase));    //Proof custom paramter is available ----------------------------
    Serial.print("  ");
    Serial.println(String(double_press));       //Proof custom paramter is available ----------------------------
  
    // You can use different ways to invoke Alexa to modify the devices state, using the custom parameters via AP:
    // "Alexa, turn on 'smart_home_phrase'"
    // "Alexa, turn on 'double_press'"
    
    // Add virtual devices
    fauxmo.addDevice(ID_REMOTE);
    fauxmo.addDevice(ID_PARKDOOR);

        
    fauxmo.onSetState([](unsigned char device_id, const char * device_name, bool state, unsigned char value) {
        
          // If you have to do something more involved here set a flag and process it in your main loop.
        
        Serial.printf("[MAIN] Device #%d (%s) state: %s value: %d\n", device_id, device_name, state ? "ON" : "OFF", value);

        // Checking for device_id is simpler if you are certain about the order they 
        //    are loaded and it does not change.
        // Otherwise comparing the device_name is safer.

        if (strcmp(device_name, ID_REMOTE)==0) {
            digitalWrite(PIN_DOOR, state ? HIGH : LOW);
        } else if (strcmp(device_name, ID_PARKDOOR)==0) {
            digitalWrite(PIN_PARKDOOR, state ? HIGH : LOW);
        } 
    });
    
    WiFi.persistent(true);
    WiFi.setAutoConnect(true);
    WiFi.setAutoReconnect(true);

}

void loop() {

    // fauxmoESP uses an async TCP server but a sync UDP server
    // Therefore, we have to manually poll for UDP packets

    fauxmo.handle();
    
    unsigned long currentMillis = millis();
    

//>>>>>>>>  GPIO 3 button to reset the WiFi credentials and restart the ESP,
//>>>>>>>>  reset on 4s (longButton) button hold
    button = digitalRead(wifiReSetPIN);
    if ((button == HIGH) && (buttonFlag == false)) {
        Serial.println("WiFi config button HIGH");
        buttonMillis = currentMillis;
        buttonFlag = true;
      }  
    else if ((button == HIGH) && (buttonFlag == true) && (currentMillis - buttonMillis >= longButton)) {
        Serial.println("WiFi config reset & ESP reset");
        delay(2000);
        wifiManager.resetSettings();
        delay(200);
        int var = 0;
        while (var < 13) {
          digitalWrite(PIN_PARKDOOR, HIGH);
          delay(1);
          digitalWrite(PIN_PARKDOOR, LOW);
          delay(199);
          var ++;
        }
        //Serial.println("Just before ESP.restart");
        ESP.restart();
      }
    else if ((button == LOW) && (buttonFlag == true)) {
        buttonFlag = false; 
      }
    else { //do nothing
      }

}```

**Comment by pvint** [comment] 2020-11-13 02:09
Haven't had time to look at this yet... will be busy for the next couple days, but hopefully Monday I can have a look.

**Comment by ddweber456** [comment] 2020-11-20 16:18
@pvint Now that the discovery resolution is looking very good, maybe you can give your thoughts on this issue.  I'm still not sure if the hard reset is a WiFiManager or FauxmoESP issue.  I'm thinking it might have something to do with the UDP vs STA mode.  Your help is greatly appreciated.

**Comment by pvint** [comment] 2020-11-20 17:35
I've been able to reproduce the issue (noting the steps for my own reference):

1. Upload sketch with Erase Flash "All Flash Contents"
2. Set the AP in WiFiManager (which is really cool, BTW - I'll be using this in the future!)
3. Once it is connected, I can ping the device, but "Discover" does not work.
4. Reset the 8266, then discover works.

I'll dig into it a bit more.

**Comment by ddweber456** [comment] 2020-11-20 17:47
> Set the AP in WiFiManager (which is really cool, BTW - I'll be using this in the future!)

Thanks, that make me feel good.
The code needs to be updated to ArduinoJson library v 6.  Right now the code uses the latest of v 5 (5.13.5).

**Comment by pvint** [comment] 2020-11-22 21:10
Just looking at this a bit more, and I'm able to repeat it every time. I did a couple packet captures to try to see what's happening.

From the first try after setting the AP in WiFiManager (when it fails to discover):
![Selection_103](https://user-images.githubusercontent.com/608740/99917177-a81f8f80-2cdc-11eb-8bbb-fbf910902d06.png)

And after resetting the ESP8266, when the discovery works:
![Selection_104](https://user-images.githubusercontent.com/608740/99917188-b9689c00-2cdc-11eb-9bb4-f10063727cff.png)

Note the line in red on the first one (where it fails), the ESP is sending a RST, ACK to the Amazon (which pretty much amounts to "bugger off, I'm closing the connection"), and because of this the Amazon device simply gives up.

Very strange, and not sure why yet.

**Comment by ddweber456** [comment] 2020-11-24 17:17
Thanks for doing the investigation.  I was waiting to see what developed but have heard nothing yet. At least we know what's happening.  Any ideas as to why?

**Comment by ddweber456** [comment] 2020-11-25 04:37
Paul, I just posted some more details on this issue, please see #1142 WiFiManager.  Sorry I couldn't figure out how to give you the exact link.  Thanks again for looking into this.

I'll try to figure out how to link this to WiFiManager so other can easily follow the details. (not to night)  :-)

**Comment by ddweber456** [comment] 2020-11-29 23:38
I have been using this mod for several days and have not been able to get the Echo not to discover the new devices.

I would be interested in knowing if anyone else is still having issues getting Echo doing a consistent discovery.  If so please post here.

**Comment by marauderlabs** [comment] 2020-12-31 22:13
I face the same issue. For me it's worse. I can't get it to discover even with a reset.

**Comment by ddweber456** [comment] 2021-01-01 14:26
@marauderlabs - Make sure you are using FauzmoESP v3.1.2 or greater.  Via the phone app or web alexa.amazon.com delete any past discoveries of the ESP you are trying to discover and delete any past discoveries with the same Alexa device name.

**Comment by GAndrews98** [comment] 2021-01-06 04:29
I have the same issue. My Echo dot won't discover the ESP even with a reset. It used to work consistently a few months ago, but for the past few weeks I haven't been able to get it to discover the device at all.

**Comment by pvint** [comment] 2021-01-15 19:48
@GAndrews98  Please make sure you are updated - versions below 3.1.2 will no longer work.

@ddweber456  Given that this seems to be fixed in the current master branch of ESP8266-Arduino (See issue referenced above), I'm closing this. Who knows when it will actually be released though ;)

**Closed by pvint** 2021-01-15 19:48 UTC
